// Реестр рецептов: имя рецепта в манифесте → функция рисования.
import type { Recipe } from '../ArtFactory';
import { bedrock } from './bedrock';
import { backdrop, floor } from './floor';
import { boom, debris, dust, flameEnd, flameH, flameV, glow, glowSoft, smoke, spark, vignette } from './fx';
import { ghost, heroArm, heroBeltStick, heroBody, heroHead, heroLeg, heroPouch, heroScarf } from './hero';
import { boot, crackMark, dangerRing, paw, routeDot, tape, tapeCenter, target, x2, zzz } from './hints';
import {
  koboldBody,
  koboldCandle,
  koboldEyes,
  koboldFoot,
  koboldHead,
  koboldSleep,
  steam,
  stunStar,
} from './kobold';
import {
  daylight,
  dynPlanted,
  fuseSpark,
  lair,
  lantern,
  lift,
  liftFront,
  mushroom,
  nuggetBig,
  nuggetSmall,
  rubble,
  scorch,
  shadow,
  stickItem,
  timberBeam,
  timberPost,
} from './props';
import { hard, pocket, pocketSpark, rock, rockCracked, vein } from './rock';

export const recipes: Record<string, Recipe> = {
  floor,
  backdrop,
  bedrock,
  rock,
  rockCracked,
  hard,
  vein,
  pocket,
  pocketSpark,
  lift,
  liftFront,
  daylight,
  lair,
  mushroom,
  timberPost,
  timberBeam,
  lantern,
  stickItem,
  nuggetBig,
  nuggetSmall,
  dynPlanted,
  fuseSpark,
  shadow,
  scorch,
  rubble,
  heroBody,
  heroHead,
  heroLeg,
  heroArm,
  heroScarf,
  heroPouch,
  heroBeltStick,
  koboldBody,
  koboldHead,
  koboldSleep,
  koboldFoot,
  koboldEyes,
  koboldCandle,
  stunStar,
  steam,
  boom,
  flameH,
  flameV,
  flameEnd,
  debris,
  smoke,
  spark,
  dust,
  glow,
  glowSoft,
  tape,
  tapeCenter,
  crackMark,
  x2,
  boot,
  paw,
  target,
  ghost,
  routeDot,
  zzz,
  dangerRing,
  vignette,
};
